#ifndef CACHEGRAND_FIBER_CONTEXT_H
#define CACHEGRAND_FIBER_CONTEXT_H

#define FIBER_CONTEXT_NUM_REGISTRIES (22)
#define FIBER_CONTEXT_SP_PC_OFFSET   (0x14)
#define FIBER_CONTEXT_SP_ABRT_OFFSET (0x13)

#endif //CACHEGRAND_FIBER_CONTEXT_H
