#ifndef CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_VOIDPTR_H
#define CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_VOIDPTR_H

#define RING_BOUNDED_QUEUE_SPSC_ITEM_TYPE         void*
#define RING_BOUNDED_QUEUE_SPSC_ITEM_NAME         voidptr
#define RING_BOUNDED_QUEUE_SPSC_ABI_EXPOSE_FOUND  0

#include "ring_bounded_queue_spsc_generic.h"

#endif //CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_VOIDPTR_H
