#ifndef CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_UINT128_H
#define CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_UINT128_H

#define RING_BOUNDED_QUEUE_SPSC_ITEM_TYPE         uint128_t
#define RING_BOUNDED_QUEUE_SPSC_ITEM_NAME         uint128
#define RING_BOUNDED_QUEUE_SPSC_ABI_EXPOSE_FOUND  1

#include "ring_bounded_queue_spsc_generic.h"

#endif //CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_UINT128_H
