#ifndef CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_UINT64_H
#define CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_UINT64_H

#define RING_BOUNDED_QUEUE_SPSC_ITEM_TYPE         uint64_t
#define RING_BOUNDED_QUEUE_SPSC_ITEM_NAME         uint64
#define RING_BOUNDED_QUEUE_SPSC_ABI_EXPOSE_FOUND  1

#include "ring_bounded_queue_spsc_generic.h"

#endif //CACHEGRAND_RING_BOUNDED_QUEUE_SPSC_UINT64_H
