#ifndef CACHEGRAND_VERSION_H

extern const char* CACHEGRAND_CMAKE_CONFIG_ARCH_TARGET;
extern const char* CACHEGRAND_CMAKE_CONFIG_VERSION_GIT;
extern const char* CACHEGRAND_CMAKE_CONFIG_BUILD_DATE_TIME;

#define CACHEGRAND_VERSION_H

#endif //CACHEGRAND_VERSION_H
