#ifndef CACHEGRAND_CMAKE_CONFIG
#define CACHEGRAND_CMAKE_CONFIG

#ifdef __cplusplus
extern "C" {
#endif

#define CACHEGRAND_SRC_PATH ((const char*)__FILE__ + CACHEGRAND_CMAKE_CONFIG_SOURCE_PATH_SIZE)

extern const char *CACHEGRAND_CMAKE_CONFIG_ARCH_TARGET;
extern const char *CACHEGRAND_CMAKE_CONFIG_VERSION_GIT;
extern const char *CACHEGRAND_CMAKE_CONFIG_BUILD_DATE_TIME;
extern const char *CACHEGRAND_CMAKE_CONFIG_BUILD_TYPE;

#ifdef __cplusplus
}
#endif

#endif //CACHEGRAND_CMAKE_CONFIG
